version: 2
updates:
  # Flutter dependencies
  - package-ecosystem: pub
    directory: /flutter
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    open-pull-requests-limit: 5

  # Python backend dependencies
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: saturday
      time: "09:00"
    open-pull-requests-limit: 5
