from pydantic import BaseModel, Field, computed_field
from typing import Optional, List
from enum import Enum


class WorkoutType(str, Enum):
    AMRAP = "amrap"
    EMOM = "emom"
    FOR_TIME = "for_time"
    TABATA = "tabata"
    INTERVALS = "intervals"
    STOPWATCH = "stopwatch"
    CUSTOM = "custom"


class Movement(BaseModel):
    name: str
    reps: Optional[int | str] = None
    duration: Optional[int] = None
    weight: Optional[str] = None
    notes: Optional[str] = None


class AudioCue(BaseModel):
    time: int
    message: str
    type: str = "announcement"


class Interval(BaseModel):
    duration: int
    type: str = "work"


class TimerConfig(BaseModel):
    """Timer configuration computed from intervals for UI compatibility."""

    type: str  # "countdown" or "intervals"
    total_seconds: Optional[int] = None
    rounds: Optional[int] = None
    intervals: List[Interval] = Field(default_factory=list)
    audio_cues: List[AudioCue] = Field(default_factory=list)
    rest_between_rounds: Optional[int] = None


class ParsedWorkout(BaseModel):
    """
    Internal parsed workout model.
    Stores simplified data (just intervals), computes UI fields on serialization.
    Audio cues are generated by the app based on intervals, not by LLM.
    """

    workout_type: WorkoutType
    movements: List[Movement] = Field(default_factory=list)
    intervals: List[Interval] = Field(default_factory=list)
    raw_text: str
    ai_interpretation: Optional[str] = None

    @computed_field
    @property
    def duration(self) -> Optional[int]:
        """Total workout duration in seconds (sum of all intervals)."""
        if not self.intervals:
            return None
        return sum(interval.duration for interval in self.intervals)

    @computed_field
    @property
    def rounds(self) -> Optional[int]:
        """Number of work intervals (rounds)."""
        work_intervals = [i for i in self.intervals if i.type == "work"]
        return len(work_intervals) if work_intervals else None

    @computed_field
    @property
    def time_cap(self) -> Optional[int]:
        """Time cap (same as duration for capped workouts)."""
        if (
            self.workout_type == WorkoutType.FOR_TIME
            and self.duration
            and self.duration > 0
        ):
            return self.duration
        return None

    @computed_field
    @property
    def rest_between_rounds(self) -> Optional[int]:
        """Rest duration between rounds (if consistent rest intervals exist)."""
        rest_intervals = [i for i in self.intervals if i.type == "rest"]
        if rest_intervals:
            # Return the first rest interval duration as representative
            return rest_intervals[0].duration
        return None

    @computed_field
    @property
    def timer_config(self) -> TimerConfig:
        """Build timer_config object for UI compatibility."""
        # Determine timer type based on workout type
        if self.workout_type in [
            WorkoutType.EMOM,
            WorkoutType.TABATA,
            WorkoutType.INTERVALS,
        ]:
            timer_type = "intervals"
        elif self.workout_type == WorkoutType.STOPWATCH:
            timer_type = "stopwatch"
        else:
            timer_type = "countdown"

        return TimerConfig(
            type=timer_type,
            total_seconds=self.duration,
            rounds=self.rounds,
            intervals=self.intervals,
            audio_cues=[],  # Generated by app, not LLM
            rest_between_rounds=self.rest_between_rounds,
        )


class WorkoutParseRequest(BaseModel):
    workout_text: str = Field(..., min_length=1, description="Raw workout description")

    class Config:
        json_schema_extra = {
            "example": {
                "workout_text": "AMRAP 20min:\n10 Wall Balls (20/14 lbs)\n10 Box Jumps (24/20 in)\n10 Burpees"
            }
        }
